# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - hsg-primo-dev

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_895b76b8337a43d6981b2bb37fb50c8f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_39d30e5f0de544a2b828f0207db0a040 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_895b76b8337a43d6981b2bb37fb50c8f }}/primo-dev:${{ github.sha }}
        file: ./.ci/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hsg-primo-dev'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_db02d82405a047bc903440982384227e }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_895b76b8337a43d6981b2bb37fb50c8f }}/primo-dev:${{ github.sha }}'